### ISSUE TITLE
README.md build instructions don't work

### ISSUE THREAD

**Issue by Bill-Kunj** [rchain-community/rhovision-website#9]
I tried a fresh pull and went through the README.md Build instructions https://github.com/rchain-community/rhovision-website#build

No worky.
```
me@bill:/media/me/Elements/OC/rhovision-website$ yarn add cmark-gfm-js
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved 1 new dependency.
info Direct dependencies
└─ cmark-gfm-js@1.1.7
info All dependencies
└─ cmark-gfm-js@1.1.7
Done in 0.91s.
me@bill:/media/me/Elements/OC/rhovision-website$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.13s.
me@bill:/media/me/Elements/OC/rhovision-website$ node md2html.js pages/filr.md > html/file.html
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/media/me/Elements/OC/rhovision-website/md2html.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.12.1
```

**Comment by Bill-Kunj** [comment]
After checking some spelling, I cloned from scratch and tried again. Same results
```
me@bill:/media/me/Elements/OC$ git clone git@github.com:rchain-community/rhovision-website.git
Cloning into 'rhovision-website'...
remote: Enumerating objects: 126, done.
remote: Counting objects: 100% (126/126), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 126 (delta 50), reused 46 (delta 16), pack-reused 0
Receiving objects: 100% (126/126), 46.63 KiB | 1.06 MiB/s, done.
Resolving deltas: 100% (50/50), done.
me@bill:/media/me/Elements/OC$ cd rhovision-website
me@bill:/media/me/Elements/OC/rhovision-website$ ls
html  LICENSE  package.json  pages  pictures  README.md  src  web.js
me@bill:/media/me/Elements/OC/rhovision-website$ yarn add cmark-gfm-js
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ cmark-gfm-js@1.1.7
info All dependencies
└─ cmark-gfm-js@1.1.7
Done in 2.08s.
me@bill:/media/me/Elements/OC/rhovision-website$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.14s.
me@bill:/media/me/Elements/OC/rhovision-website$ node md2html.js pages/file.md >html/file.html
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/media/me/Elements/OC/rhovision-website/md2html.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.12.1
```

**Comment by jimscarver** [comment]
Fixed path to md2html and filename.

**Comment by Bill-Kunj** [comment]
The README.md instructions still do not work. See below error message

```
me@bill:~$ mkdir blah
me@bill:~$ cd $_
me@bill:~/blah$ git clone git@github.com:rchain-community/rhovision-website.git
Cloning into 'rhovision-website'...
remote: Enumerating objects: 129, done.
remote: Counting objects: 100% (129/129), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 129 (delta 52), reused 46 (delta 16), pack-reused 0
Receiving objects: 100% (129/129), 47.28 KiB | 396.00 KiB/s, done.
Resolving deltas: 100% (52/52), done.
me@bill:~/blah$ cd *
me@bill:~/blah/rhovision-website$ yarn add cmark-gfm-js
yarn add v1.22.19
warning ../../package.json: No license field
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ cmark-gfm-js@1.1.7
info All dependencies
└─ cmark-gfm-js@1.1.7
Done in 0.76s.
me@bill:~/blah/rhovision-website$ yarn install
yarn install v1.22.19
warning ../../package.json: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.08s.
me@bill:~/blah/rhovision-website$ node src/md2html.js pages/home.md >html/home.html
me@bill:~/blah/rhovision-website$ node web.jw
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/home/me/blah/rhovision-website/web.jw'
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.12.1
```
